apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-application
  namespace: argocd
spec: 
  project: default

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

  source:
    repoURL: https://github.com/jakdimi/helm-test.git
    path: helm-test
    helm:
      values: |
        replicas: 1

